#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html

server_config=\
"server {
	listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By 316245-web-01;
    root   /var/www/html;
    index  index.html index.htm;
    location /hbnb_static {
        alias /data/web_static/current/;
    }
    location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me) {
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
    }"

bash -c "echo -e '$server_config' > /etc/nginx/sites-available/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
