#!/usr/bin/env bash
# a script used to configure a Nginx server

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello Wolrd!" > /var/www/html/index.html
touch /var/www/html/404_error.html
echo "Ceci n'est pas une page" > /var/www/html/404_error.html

echo "server {
    listen 80;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404_error.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
