#!/usr/bin/env bash
# a script used to configure a Nginx server

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello Wolrd!" > /var/www/html/index.html
touch /var/www/html/404_error.html
echo "Ceci n'est pas une page" > /var/www/html/404_error.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By 316245-web-01;
    root   /var/www/html;
    index  index.html index.htm;

    location /hbnb_static {
        alias /data/web_static/current/;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html{
		internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
