#!/usr/bin/env bash
# Configuring Nginx so that its HTTP response contains a custom header
apt-get update
apt-get install -y nginx

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
}" > /etc/nginx/sites-available/default

service nginx restart
