#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Requirements:
# 	- Configure HAproxy so that it send traffic to web-01 and web-02
# 	- Distribute requests using a roundrobin algorithm
# 	- Make sure that HAproxy can be managed via an init script
# 	- Make sure that your servers are configured with the right
# 	  hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.
#	- For your answer file, write a Bash script that configures a new Ubuntu
#	  machine to respect above requirements

apt-get install --no-install-recommends -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get install -y haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 316245-web-01 100.25.20.203:80 check
    server 316245-web-02 18.235.243.68:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
