#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Requirements:
# 	- Configure HAproxy so that it send traffic to web-01 and web-02
# 	- Distribute requests using a roundrobin algorithm
# 	- Make sure that HAproxy can be managed via an init script
# 	- Make sure that your servers are configured with the right
# 	  hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.
#	- For your answer file, write a Bash script that configures a new Ubuntu
#	  machine to respect above requirements

apt-get install --no-install-recommends -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get install -y haproxy=2.0.\*

# Configure HAProxy
sudo cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon

defaults
    log global
    mode http
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
	server 316245-web-01 100.25.20.203:80 check
	server 316245-web-02 18.235.243.68:80 check
EOF

# Enable HAProxy management via init script
sudo systemctl enable haproxy

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy
