#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Requirements:
# 	- Configure HAproxy so that it send traffic to web-01 and web-02
# 	- Distribute requests using a roundrobin algorithm
# 	- Make sure that HAproxy can be managed via an init script
# 	- Make sure that your servers are configured with the right
# 	  hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.
#	- For your answer file, write a Bash script that configures a new Ubuntu
#	  machine to respect above requirements

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update -y
sudo apt-get install -y haproxy=2.8.\*

# Configure HAProxy
echo \
"global
	log /dev/log    local0
	log /dev/log    local1 notice
	daemon

defaults
	log global
	mode http

frontend haproxy_main
	bind *:80
	option http-server-close
	default_backend nginx_back

backend nginx_back
	balance roundrobin
	option http-server-close
	server 316245-web-01 100.25.20.203:80 check
	server 316245-web-02 18.235.243.68:80 check" | sudo tee /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the changes
sudo service haproxy restart
