#!/usr/bin/env bash
# A bash script that pings an IP addresss passed as an argument.
# Requirements:
# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Ping the IP 5 times
regex='^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]$'
if [[ $1 =~ $regex ]]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
