#!/usr/bin/env bash
# Binding nginx to port 80
# sed -E -i 's/listen\s*[0-9]+;/listen 80 default_server;/g' /etc/nginx/nginx.conf
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
