#!/usr/bin/env bash
# A Bash script that displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line.
counter=1
while ((counter <= 10))
do
	echo "Best School"
	if ((counter == 9 ))
	then
		echo "Hi"
	fi
	(( counter++ ))
done
