#!/usr/bin/env bash
# A Bash script that displays Best School 10 times using while loop.
declare -i counter=1
while (( counter <= 10 ))
do
	if (( counter == 4 ))
	then
		echo "bad luck"
	elif (( counter == 8 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
