#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
hour=0
max_hour=13
minute=1
max_minute=60
while(( hour < max_hour ))
do
	echo "Hour: $hour"
	while ((minute < max_minute ))
	do
		echo $minute
		((minute++))
	done
	((hour++))
	minute=1
done
