#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
sudo pkill -f apache2
sudo chmod 664 /etc/nginx/nginx.conf
sudo sed -Ei 's/.*user.*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -Ei 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
