#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
sudo pkill -f apache2
sudo chmod 664 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
