#!/usr/bin/env bash
# Your SSH client configuration must be configured to use the private key
# ~/.ssh/school
# Your SSH client configuration must be configured to refuse to authenticate
# using a password

Host *
	HostName 100.25.20.203
	User ubuntu
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	GSSAPIAuthentication yes
	HashKnownHosts yes
	SendEnv LANG LC_*
